export class Status{
  rateLimitStatus: string;
  accessLevel: number;
  // createdAt
  // id
  // text
  // displayTextRangeStart
  // displayTextRangeEnd
  // source
  // nReplyToStatusId
  // inReplyToUserId
  // favoriteCount
  // inReplyToScreenName
  // geoLocation
  // place
  // retweetCount
  // lang
  // retweetedStatus
  // userMentionEntities
  // hashtagEntities
  // mediaEntities
  // symbolEntities
  // currentUserRetweetId
  // scopes
  // user
  // withheldInCountries
  // quotedStatus
  // quotedStatusId
  // quotedStatusPermalink
  // contributors
  // truncated"
  // retweetedByMe
  // urlentities
  // retweet
  // favorited
  // retweeted
  // possiblySensitive
  constructor(){}
}
